version: '3.9'

services:
  app01:
    build: 
      context: .
      args:
        SSH_PASSWORD: ${SSH_PASSWORD}
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - ${APP_PORT}:8501
      - ${SSH_PORT}:22


