version: '3.8'
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: gzginfra-npm
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "npmdb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - npmdb

  # Base de datos mysql usada solo para nginx manager
  npmdb:
    container_name: gzginfra-npmdb
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./npm/mysql:/var/lib/mysql

  # Base de datos Redis de uso general
  redis:
    container_name: gzginfra-redis
    image: redis:latest
    restart: unless-stopped
    command: redis-server --appendonly yes --appendfsync everysec --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"

  # Base de datos postgresql de uso general
  postgresdb:
    image: postgres:latest
    container_name: gzginfra-postgresdb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./postgrsql/db:/var/lib/postgresql/data

  # Administrador de bases de datos postgresql
  pgadmin:
    image: dpage/pgadmin4
    container_name: gzginfra-pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./postgrsql/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgresdb

  keycloak:
    image: bitnami/keycloak
    container_name: gzginfra-keycloak
    user: '${UID}'
    environment:
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_HOST=postgresdb
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_USER=${POSTGRES_USER}
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=${POSTGRES_PASSWORD}

      - KEYCLOAK_PRODUCTION=true

      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_HTTPS_PORT=8443

      - KEYCLOAK_ENABLE_HTTPS=true
      - KEYCLOAK_HTTPS_USE_PEM=true
      - KEYCLOAK_HTTPS_CERTIFICATE_FILE=/opt/bitnami/keycloak/certs/fullchain.pem
      - KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE=/opt/bitnami/keycloak/certs/privkey.pem

      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak/certs/fullchain.pem:/opt/bitnami/keycloak/certs/fullchain.pem
      - ./keycloak/certs/privkey.pem:/opt/bitnami/keycloak/certs/privkey.pem
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"
      - "8443:8443"
